Hoai_Vitaminhouse/Hoai_Vitaminhouse/Areas/Admin/Controllers/AccessController.cs
using Hoai_Vitaminhouse.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hoai_Vitaminhouse.Areas.Admin.Controllers
{
    public class AccessController : Controller
    {
        private Vitaminhouse db = new Vitaminhouse ();
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(FormCollection frm)
        {
            string email = frm["email"];
            string password = frm["password"];
            email = email.Trim();
            password = password.Trim();
            if (email != "" && password != "")
            {
                Account admin = db.Accounts.Where(s => s.AccountEmail.Equals(email) && s.AccountPassword.Equals(password)).SingleOrDefault();
                if (admin != null)
                {
                    //Nếu là nhân viên hoặc người quản lý đang mở khóa thì có thể truy cập
                    if (((admin.AccountRole == 3) || (admin.AccountRole == 2)) && admin.AccountStatus == true)
                    {
                        Session["admin"] = admin;
                        Session["roleAdmin"] = admin.AccountRole;//Lưu trữ quyền truy cập xem là quản trị hay nhân viên

                        return Redirect("/Admin/Home/Index");
                    }
                    else
                    {
                        ViewBag.ErrorLogin = "Bạn không có quyền truy cập hoặc tài khoản đang bị khóa! ";
                        return View();
                    }
                }
                else
                {
                    ViewBag.ErrorLogin = "Đăng nhập thất bại kiểm tra lại email và password! ";
                    return View();
                }
            }
            else
            {
                ViewBag.ErrorLogin = "Phải nhập đầy đủ Email và Password! ";
                return View();
            }
        }

        public ActionResult Logout()
        {
            Session["admin"] = null;

            return Redirect("/Admin/Access/Login");
        }
    }
}

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Controllers/AccountsController.cs
using Hoai_Vitaminhouse.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hoai_Vitaminhouse.Controllers
{
    public class AccountsController : Controller
    {
        private Vitaminhouse db = new Vitaminhouse();

        public ActionResult Logout()
        {
            Session["user"] = null;
            return Redirect("/");
        }

        public ActionResult Login()
        {
            if (Session["user"] == null)
            {
                return View();
            }
            return Redirect("/");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(FormCollection frm)
        {
            if (ModelState.IsValid)
            {
                string email = frm["email"];
                string password = frm["password"];

                Account user = db.Accounts.Where(s => s.AccountEmail.Equals(email) && s.AccountPassword.Equals(password)).SingleOrDefault();
                if (user != null)
                {
                    if (user.AccountStatus)
                    {
                        Session["user"] = user;//Thực hiện gán vào session
                        return Redirect("/");
                    }
                    else
                    {
                        ViewBag.errorLogin = "Tài khoản của bạn đang bị khóa!";
                    }
                }
                else
                {
                    ViewBag.errorLogin = "Vui lòng kiểm tra lại email hoặc mật khẩu! ";
                }

            }
            return View();
        }

        public ActionResult Register()
        {
            if (Session["user"] == null)
            {
                return View();
            }
            return Redirect("/");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "AccountName,AccountPhone,AccountEmail,AccountPassword,AccountAddress")] Account taiKhoan, FormCollection frm)
        {
            try
            {
                string confirmPassword = frm["confirmPassword"];
                if (confirmPassword != taiKhoan.AccountPassword)
                {
                    ViewBag.errorRegister = "Mật khẩu xác nhận không khớp! ";
                    return View(taiKhoan);
                }

                var tkcheck = db.Accounts.Where(tk => tk.AccountEmail == taiKhoan.AccountEmail);
                if (tkcheck.Count() == 0)
                {
                    if (ModelState.IsValid)
                    {
                        taiKhoan.AccountStatus = true;//Tình trạng là đang mở hoạt động bình thường
                        taiKhoan.AccountRole = 1;//Tài khoản mặc định là tài khoản khách hàng
                        db.Accounts.Add(taiKhoan);
                        db.SaveChanges();
                    }
                    return RedirectToAction("Login");
                }
                else
                {
                    ViewBag.errorRegister = "Email đã tồn tại! ";
                    return View(taiKhoan);
                }
            }
            catch (Exception ex)
            {
                ViewBag.errorRegister = "Lỗi " + ex.Message;
                return View(taiKhoan);
            }
        }


        public ActionResult ChangeInfo()
        {
            if (Session["user"] != null)
            {
                Account taiKhoan = Session["user"] as Account;
                return View(taiKhoan);
            }
            return Redirect("/");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangeInfo([Bind(Include = "AccountId,AccountName,AccountPhone,AccountEmail,AccountPassword,AccountAddress, AccountRole, AccountStatus")] Account taiKhoan)
        {
            try
            {
                if (taiKhoan.AccountName.Trim() == "")
                {
                    ViewBag.errorUpdateTaikhoan = "Họ tên không được để trống! ";
                    return View(taiKhoan);
                }
                var tkcheck = db.Accounts.Where(tk => (tk.AccountEmail == taiKhoan.AccountEmail) && tk.AccountId != taiKhoan.AccountId);
                if (tkcheck.Count() == 0)
                {
                    db.Entry(taiKhoan).State = EntityState.Modified;
                    db.Configuration.ValidateOnSaveEnabled = false;
                    db.SaveChanges();

                    Session["user"] = taiKhoan;//Lưu lại thông tin của khi cập nhật

                    return RedirectToAction("Detail");
                }
                else
                {
                    ViewBag.errorUpdateTaikhoan = "Email đã được tài khoản khác sử dụng! ";
                    return View(taiKhoan);
                }
            }
            catch (Exception ex)
            {
                ViewBag.errorUpdateTaikhoan = "Lỗi " + ex.Message;
                return View(taiKhoan);
            }
        }

        public ActionResult ChangePassword()
        {
            if (Session["user"] != null)
            {
                Account taiKhoan = Session["user"] as Account;
                return View(taiKhoan);
            }
            return Redirect("/");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword([Bind(Include = "AccountId,AccountName,AccountPhone,AccountEmail,AccountPassword,AccountAddress, AccountRole, AccountStatus")] Account taiKhoan)
        {
            try
            {
                string cu = Request["oldPassword"];
                string moi = Request["newPassword"];
                string xacnhan = Request["confirmPassword"];

                if (cu != null && moi != null && xacnhan != null)
                {
                    if (cu != "" && moi != "" && xacnhan != "")
                    {
                        if (moi == xacnhan)
                        {
                            if (moi.Length >= 3 && moi.Length <= 30)
                            {
                                Account tk = Session["user"] as Account;//Lấy dữ liệu user đang lưu ở session
                                if (cu == tk.AccountPassword + "")
                                {
                                    taiKhoan.AccountPassword = moi;
                                    db.Entry(taiKhoan).State = EntityState.Modified;
                                    Session["user"] = taiKhoan;
                                    db.SaveChanges();
                                    return RedirectToAction("Detail");

                                }
                                else
                                {
                                    ViewBag.LoiMatKhau = "Mật khẩu cũ không khớp!";
                                    return View(taiKhoan);
                                }
                            }
                            else
                            {
                                ViewBag.LoiMatKhau = "Độ dài mật khẩu mới >=3 và <=30!";
                                return View(taiKhoan);
                            }
                        }
                        else
                        {
                            ViewBag.LoiMatKhau = "Mật khẩu mới và xác nhận không khớp!";
                            return View(taiKhoan);
                        }
                    }
                    else
                    {
                        ViewBag.LoiMatKhau = "Không được để trống trường dữ liệu nào!";
                        return View(taiKhoan);
                    }
                }
                else
                {
                    ViewBag.LoiMatKhau = "Không được để trống trường dữ liệu nào!";
                    return View(taiKhoan);
                }
            }
            catch (Exception ex)
            {
                ViewBag.LoiMatKhau = "Lỗi " + ex.Message;
                return View(taiKhoan);
            }
        }


        public ActionResult Detail()
        {
            if (Session["user"] != null)
            {
                Account taiKhoan = Session["user"] as Account;
                List<Order> listDonHang = db.Orders.Where(p => p.AccountId == taiKhoan.AccountId)
                                                   .OrderByDescending(p => p.OrderDate).ToList();

                ViewBag.listDonHangByMaTK = listDonHang;

                return View(taiKhoan);
            }
            return RedirectToAction("Login");
        }
    }
}

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Areas/Admin/Views/Shared/_FooterAdmin.cshtml
<footer id="footer" class="footer">
    <div class="copyright">
        Copyright <strong> &copy; </strong> <b> Phạm Thị Hoài - 2022 </b>
    </div>
</footer>
<a href="#" class="back-to-top d-flex align-items-center justify-content-center">
    <i class="bi bi-arrow-up-short"></i>
</a>

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Areas/Admin/Views/Shared/_HeaderAdmin.cshtml
@model Hoai_Vitaminhouse.Models.Account

<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center">
        <a href="@Url.Action("Index","Home")" class="logo flex-jc">
            <img src="~/Areas/Admin/Assets/img/logo_3.png" style="max-height: 55px !important;"/>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">
            <li class="nav-item dropdown pe-3">

                <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-person-fill" style="font-size: 30px;"></i>
                    <span class="d-none d-md-block dropdown-toggle ps-2">
                       @Model.AccountName
                    </span>
                </a><!-- End Profile Iamge Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                    <li class="dropdown-header">
                        <h6>@Model.AccountEmail</h6>
                        <span>@Model.AccountPhone</span>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="@Url.Action("Index","Accounts")">
                            <i class="bi bi-person"></i>
                            <span>Tài khoản</span>
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="@Url.Action("ChangeInfo","Accounts")">
                            <i class="bi bi-pencil-square"></i>
                            <span>Sửa tài khoản</span>
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="@Url.Action("ChangePassword","Accounts")">
                            <i class="bi bi-key"></i>
                            <span>Đổi mật khẩu</span>
                        </a>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="@Url.Action("Logout","Access")">
                            <i class="bi bi-box-arrow-right"></i>
                            <span>Đăng xuất</span>
                        </a>
                    </li>

                </ul><!-- End Profile Dropdown Items -->
            </li><!-- End Profile Nav -->

        </ul>
    </nav><!-- End Icons Navigation -->

</header>

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <!-- Thiết lập chung -->
    @{
        Html.RenderPartial("_TitleHeadAdmin");
    }


    <!-- Template Main CSS File -->
    <link href="~/Areas/Admin/Assets/css/style.css" rel="stylesheet">
    <link href="~/Areas/Admin/Assets/css/footer.css" rel="stylesheet">
    <link href="~/Areas/Admin/Assets/css/main.css" rel="stylesheet">
    <link href="~/Areas/Admin/Assets/css/header.css" rel="stylesheet">
    <link href="~/Areas/Admin/Assets/css/slide-bar.css" rel="stylesheet">

    <!-- Template CSSPartial File -->
    @RenderSection("CSSPartial", required: false)


</head>

<body>
   
    <!-- ======= Header ======= -->
    @{
        Html.RenderAction("_HeaderAdmin","Home");
    }
    <!-- End Header -->
    <!-- ======= Sidebar ======= -->
    @{
        Html.RenderPartial("_SidebarAdmin");
    }
    <!-- End Sidebar-->
    <!-- ======= Main ======= -->
    <main id="main" class="main">
        <div class="container">
            @{
                Html.RenderPartial("_PageTitleAdmin");
            }
            <!-- End Page Title -->

            
                @RenderBody()
            
        </div>
    </main>
    <!-- End #main -->
    <!-- ======= Footer ======= -->
    @{
        Html.RenderPartial("_FooterAdmin");
    }
    <!-- End Footer -->
    <!-- Vendor JS Files -->
    <script src="~/Areas/Admin/Assets/vendor/bootstrap/js/bootstrap.bundle.js"></script>

    <!-- Template Main JS File -->
    <script src="~/Areas/Admin/Assets/js/main.js"></script>

</body>
</html>

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Areas/Admin/Views/Shared/_PageTitleAdmin.cshtml
<div class="pagetitle">
    <h1 style="text-align: center;"> @ViewBag.Title</h1>
</div>

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Areas/Admin/Views/Shared/_SidebarAdmin.cshtml
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">
        <li class="nav-heading" style="margin-top: 0px; color: #18543b;">Quản lý</li>

        <li class="nav-item">
            <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Home" ? "active": "" )" href="@Url.Action("Index","Home")">
                <i class="bi bi-grid"></i>
                <span>Thống kê</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Categories" ? "active": "" ) " href="@Url.Action("Index","Categories")">
                <i class="bi bi-folder2-open"></i>
                <span>Danh mục</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Newspapers" ? "active": "" ) " href="@Url.Action("Index","Newspapers")">
                <i class="bi bi-newspaper"></i>
                <span>Tin tức</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Products" ? "active": "" ) " href="@Url.Action("Index","Products")">
                <i class="bi bi-box-seam"></i>
                <span>Sản phẩm</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Orders" ? "active": "" ) " href="@Url.Action("Index","Orders")">
                <i class="bi bi-bag"></i>
                <span>Đơn hàng</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Customers" ? "active": "" ) " href="@Url.Action("Index","Customers")">
                <i class="bi bi-person-circle"></i>
                <span>Khách hàng</span>
            </a>
        </li>
        @if (Convert.ToInt32(Session["roleAdmin"]) == 3)
        {
    <li class="nav-item">
        <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Employees" ? "active" : "" ) " href="@Url.Action("Index", "Employees")">
            <i class="bi bi-person-square"></i>
            <span>Nhân viên</span>
        </a>
    </li>}

        <li class="nav-heading" style="padding-top: 10px; color: #18543b;">Cá nhân</li>

        <li class="nav-item">
            <a class="nav-link @((ViewContext.RouteData.Values["Controller"].ToString() == "Accounts"  && ViewContext.RouteData.Values["Action"].ToString() == "Index")? "active": "" ) " href="@Url.Action("Index","Accounts")">
                <i class="bi bi-person"></i>
                <span>Tài khoản</span>
            </a>
        </li><!-- End Blank Page Nav -->
        <li class="nav-item">
            <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Accounts" && ViewContext.RouteData.Values["Action"].ToString() == "ChangeInfo"? "active": "" ) " href="@Url.Action("ChangeInfo","Accounts")">
                <i class="bi bi-pencil-square"></i>
                <span>Sửa tài khoản</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Accounts" && ViewContext.RouteData.Values["Action"].ToString() == "ChangePassword"? "active": "" ) " href="@Url.Action("ChangePassword","Accounts")">
                <i class="bi bi-key"></i>
                <span>Đổi mật khẩu</span>
            </a>
        </li>
    </ul>

</aside>

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Areas/Admin/Views/Shared/_TitleHeadAdmin.cshtml
<meta charset="utf-8">
<meta content="width=device-width, initial-scale=1.0" name="viewport">

<title>Cửa Hàng Đồ ăn vặt Vitamin House</title>
<meta content="" name="description">
<meta content="" name="keywords">

<link rel="icon" type="image/png" href="~/Areas/Admin/Assets/img/logo_3.png" />

<!-- Google Fonts -->
@*<link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">*@

<!-- Vendor CSS Files -->
<link href="~/Areas/Admin/Assets/vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
<link href="~/Areas/Admin/Assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
@*  *@
<link href="~/Areas/Admin/Assets/css/vitamin_house/main_vitaminhouse.css" rel="stylesheet" />
<link href="~/Areas/Admin/Assets/css/vitamin_house/home/_Index.css" rel="stylesheet" />
<link href="~/Areas/Admin/Assets/css/vitamin_house/home/_Header.css" rel="stylesheet" />
<link href="~/Areas/Admin/Assets/css/vitamin_house/home/_Slide.css" rel="stylesheet" />

<link href="~/Areas/Admin/Assets/css/vitamin_house/home/_Main.css" rel="stylesheet" />
<link href="~/Areas/Admin/Assets/css/vitamin_house/home/_Table.css" rel="stylesheet" />
<link href="~/Areas/Admin/Assets/css/vitamin_house/detail/_Detail.css" rel="stylesheet" />
<link href="~/Areas/Admin/Assets/css/vitamin_house/edit_create/_Edit_Create.css" rel="stylesheet" />

@*  *@


<style>
    .padding-table {
        padding-top: 30px;
        padding-left: 0px;
    }

    .store-pagination {
        text-align: left;
    }

        .store-pagination li {
            display: inline-block;
            width: 40px;
            height: 40px;
            line-height: 40px;
            text-align: center;
            background-color: #FFF;
            border: 1px solid #E4E7ED;
            -webkit-transition: 0.2s all;
            transition: 0.2s all;
            color: #2b2f4c;
        }

            .store-pagination li + li {
                margin-left: 5px;
            }
        .store-pagination li a{
            color:#808080;
        }
            .store-pagination li:hover {
                background-color: rgb(233, 252, 227);
                border-color: rgb(233, 252, 227);
                color: black;
            }

            .store-pagination li.active {
                background-color: #73a33e;
                border-color: #73a33e;
                color: #FFF;
                font-weight: 500;
                cursor: default;
            }

            .store-pagination li a {
                display: block;
            }

</style>