Hoai_Vitaminhouse/Hoai_Vitaminhouse/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Hoai_Vitaminhouse.Models
{
    public class Cart
    {
        Vitaminhouse db = new Vitaminhouse();
        public int iMaHang { set; get; }
        public string sTenHang { get; set; }
        public string sAnh { get; set; }
        public double dDonGia { get; set; }

        public double gGiamGia { get; set; }
        public int iSoLuong { get; set; }
        public double dThanhTien
        {
            get { return iSoLuong * (dDonGia - (dDonGia * gGiamGia)/100); }
        }



        public Cart(int MaHang)
        {
            iMaHang = MaHang;
            Product sanpham = db.Products.Single(n => n.ProductId == iMaHang);//tìm ra một sản phẩm có trong csdl với mã bằng mã truyền vào
            sTenHang = sanpham.ProductName;
            sAnh = sanpham.ProductImage;
            dDonGia = double.Parse(sanpham.ProductPrice.ToString());
            
            iSoLuong = 1;


            if(sanpham.ProductDiscount != null)
            {
                gGiamGia = double.Parse(sanpham.ProductDiscount.ToString());
            }
            else
            {
                gGiamGia = 0;
            }

        }
    }
}

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Areas/Admin/Controllers/OrdersController.cs
using Hoai_Vitaminhouse.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hoai_Vitaminhouse.Areas.Admin.Controllers
{
    public class OrdersController : Controller
    {
        private Vitaminhouse db = new Vitaminhouse();


        public ActionResult Index(int? page)
        {
            if (Session["admin"] != null)
            {
                var donHangs = db.Orders.Select(h => h).OrderByDescending(p => p.OrderId);
                int pageSizeFix = 8; //Kích thước trang
                int pageNumber = (page ?? 1);

                return View(donHangs.ToPagedList(pageNumber, pageSizeFix));
            }
            else
            {
                return Redirect("/Admin/Access/Login");
            }
        }

        public ActionResult Details(int? id)
        {
            if (Session["admin"] != null)
            {
                if (id == null)
                {
                    return Redirect("/Admin/Orders/Index");
                }

                Order donHang = db.Orders.Find(id);

                if (donHang == null)
                {
                    return Redirect("/Admin/Orders/Index");
                }

                List<OrderDetail> chiTietDonHangByID = db.OrderDetails.Where(p => p.OrderId == id).ToList();
                List<Product> dsHang = new List<Product>();

                foreach (var item in chiTietDonHangByID)
                {
                    Product sp = db.Products.Where(p => p.ProductId == item.ProductId).SingleOrDefault();
                    dsHang.Add(sp);
                }

                ViewBag.SanPhams = dsHang;
                ViewBag.ChiTietDH = chiTietDonHangByID;

                ViewBag.SumOrderSBE = chiTietDonHangByID.Sum(p => p.OrderDetailNumber);//Lấy tổng số sản phẩm
                ViewBag.OrderSumPriceFirstBE = chiTietDonHangByID.Sum(p => p.OrderDetailNumber * p.OrderDetailPrice);//Lấy tổng số tiền ban đầu
                ViewBag.OrderSumPriceDiscountBE = chiTietDonHangByID.Sum(p => (decimal)p.OrderDetailNumber * (decimal)p.OrderDetailDiscount * p.OrderDetailPrice / 100);//Lấy tổng số  tiền được giảm giá

                return View(donHang);
            }
            else
            {
                return Redirect("/Admin/Access/Login");
            }
        }

        public ActionResult Edit(int? id)
        {

            if (Session["admin"] != null)
            {
                if (id == null)
                {
                    return Redirect("/Admin/Orders/Index");
                }
                Order donHang = db.Orders.Find(id);
                if (donHang == null)
                {
                    return Redirect("/Admin/Orders/Index");
                }

                //Nếu là chờ xử lý hoặc đang giao thì mới có quyền thay đổi
                if (donHang.OrderStatus == 1 || donHang.OrderStatus == 2)
                {
                    List<string> tinhtrangDH = new List<string>
                    {
                          "Chờ xử lý","Đang giao", "Đã giao",  "Đã huỷ"
                    };
                    ViewBag.TinhTrangDH = tinhtrangDH;
                    return View(donHang);
                }
                else // Nếu tình trạng đơn hàng là 3, 4 thì sẽ không click được
                {
                    return Redirect("/Admin/Orders/Index");
                }
            }
            else
            {
                return Redirect("/Admin/Access/Login");
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderId, OrderDate, OrderAddress, OrderStatus, OrderRecipientName, OrderRecipientPhone, OrderTotalMoney, OrderNotes , AccountId")] Order donHang)
        {
            try
            {
                string tinhTrang = Request["TinhTrang"];
                donHang.OrderStatus = int.Parse(tinhTrang);


                if (donHang.OrderStatus == 4)
                {
                    //Lấy ra danh sách các mặt hàng trong đơn hàng mà 
                    List<OrderDetail> chiTietDonHangByID = db.OrderDetails.Where(p => p.OrderId == donHang.OrderId).ToList();
                    for (int i = 0; i < chiTietDonHangByID.Count; i++)
                    {
                        int idProduct = chiTietDonHangByID[i].ProductId;
                        Product sanpham = db.Products.Single(n => n.ProductId == idProduct);
                        sanpham.ProductNumber = sanpham.ProductNumber + chiTietDonHangByID[i].OrderDetailNumber;

                        db.Entry(sanpham).State = EntityState.Modified;//Lưu
                    }
                }
                db.Entry(donHang).State = EntityState.Modified;
                db.Configuration.ValidateOnSaveEnabled = false;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                List<string> tinhtrangDH = new List<string>
                {
                      "Chờ xử lý", "Đang giao", "Đã giao",  "Đã huỷ"
                };
                ViewBag.TinhTrangDH = tinhtrangDH;
                ViewBag.OrderAddressError = ex.Message;
                return View(donHang);
            }

        }
    }
}

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Controllers/CartController.cs
using Hoai_Vitaminhouse.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hoai_Vitaminhouse.Controllers
{
    public class CartController : Controller
    {


        Vitaminhouse db = new Vitaminhouse();
        public List<Cart> Laygiohang()
        {
            if (!(Session["GioHang"] is List<Cart> lstGioHang))
            {
                lstGioHang = new List<Cart>();
                Session["GioHang"] = lstGioHang;
            }
            return lstGioHang;
        }
        // GET: GioHang

        public ActionResult ThemGioHang(int iMaHang, string strURL)
        {
            // lấy session gio hang
            List<Cart> lstGioHang = Laygiohang();
            Cart sanpham = lstGioHang.Find(n => n.iMaHang == iMaHang);
            if (sanpham == null)//Trong giỏ hàng chưa có sản phẩm này
            {
                sanpham = new Cart(iMaHang);
                lstGioHang.Add(sanpham);
                return Redirect(strURL);
            }
            else//Trong giỏ hàng có sản phẩm này rồi
            {
                Product hang = db.Products.Single(n => n.ProductId == iMaHang);
                if (hang.ProductNumber > sanpham.iSoLuong)//Nếu sản phẩm trong giỏ hàng nhỏ hơn sản phẩm có thì tăng lên 1
                {
                    sanpham.iSoLuong++;
                }
                else //Nếu mà không lớn hơn thì nó chỉ bắt buộc là bằng thôi 
                {
                    sanpham.iSoLuong = hang.ProductNumber;
                }

                return Redirect(strURL);
            }
        }


        private double TongTien()
        {
            double iTongTien = 0;
            List<Cart> lstGioHang = Session["GioHang"] as List<Cart>;
            if (lstGioHang != null)
            {
                iTongTien = lstGioHang.Sum(n => n.dThanhTien);
            }
            return iTongTien;
        }

        public ActionResult Index()
        {
            List<Cart> lstGioHang = Laygiohang();
            ViewBag.TongTien = TongTien();
            return View(lstGioHang);
        }
        public ActionResult XoaGioHang(int iMaHang)
        {
            // lay gio hang tu session
            List<Cart> lstGioHang = Laygiohang();
            Cart sanpham = lstGioHang.SingleOrDefault(n => n.iMaHang == iMaHang);
            if (sanpham != null)
            {
                lstGioHang.RemoveAll(n => n.iMaHang == iMaHang);
            }
            return RedirectToAction("/Index");
        }

        public ActionResult CapNhatGioHang(int MaHang, FormCollection f)
        {
            List<Cart> lstGioHang = Laygiohang();
            Cart sanpham = lstGioHang.SingleOrDefault(n => n.iMaHang == MaHang);
            if (sanpham != null)
            {
                Product hang = db.Products.Single(n => n.ProductId == MaHang);
              
                int soluongmuon = int.Parse(f["txtSoLuongDat"].ToString());
                if (hang.ProductNumber < soluongmuon)//Nếu số lượng muốn mà nhiều hơn số lượng có thì số lượng sẽ bằng số lượng tối đa
                {
                    sanpham.iSoLuong = hang.ProductNumber;
                }
                else
                {
                    sanpham.iSoLuong = soluongmuon;
                }
                    
            }
            return RedirectToAction("Index");

        }

        public ActionResult TangSPGioHang(int MaHang)
        {
            List<Cart> lstGioHang = Laygiohang();
            Cart sanphamInGio = lstGioHang.SingleOrDefault(n => n.iMaHang == MaHang);
            if (sanphamInGio != null)//Nếu tồn tại sản phẩm
            {
                Product hang = db.Products.Single(n => n.ProductId == MaHang);
                if (hang.ProductNumber > sanphamInGio.iSoLuong)
                {
                    sanphamInGio.iSoLuong++;//Nếu mà nó vẫn đang nhỏ hơn số lượng có thì nó tăng lên 1
                }
            }
            return RedirectToAction("Index");
        }
        public ActionResult GiamSPGioHang(int MaHang)
        {
            List<Cart> lstGioHang = Laygiohang();
            Cart sanphamInGio = lstGioHang.SingleOrDefault(n => n.iMaHang == MaHang);
            if (sanphamInGio != null)//Nếu tồn tại sản phẩm
            {
                Product hang = db.Products.Single(n => n.ProductId == MaHang);
                if (sanphamInGio.iSoLuong > 1)
                {
                    sanphamInGio.iSoLuong--;//Nếu mà nó vẫn lớn hơn 1 thì trừ đi một sản phẩm trong giỏ
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult XoaTatCaGioHang()
        {
            List<Cart> lstGioHang = Laygiohang();
            lstGioHang.Clear();
            return RedirectToAction("/Index");
        }

    }
}

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Controllers/ProductsController.cs
using Hoai_Vitaminhouse.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hoai_Vitaminhouse.Controllers
{
    public class ProductsController : Controller
    {
        private Vitaminhouse db = new Vitaminhouse();

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Product sp = db.Products.Find(id);
            if (sp == null)
            {
                return Redirect("/NotFound/Index");
            }
            return View(sp);
        }


        public ActionResult FindProducts(string keyword, int? page)
        {
            if (keyword == null)
            {
                keyword = "";
            }
            ViewBag.TukhoaTimkiem = keyword;
            var hangs = db.Products.Where(p => p.ProductName.Contains(keyword)).OrderByDescending(p => p.ProductId);


            int pageSizeFix = 8; //Kích thước trang
            int pageNumber = (page ?? 1);

            return View(hangs.ToPagedList(pageNumber, pageSizeFix));


        }
    }
}

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Views/Cart/Index.cshtml
@using Hoai_Vitaminhouse.Models;
@model List<Cart>
@{
    ViewBag.Title = "GioHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- banner start -->
<section id="breadcrumb-wrapper" class="breadcrumb-w-img" style="background-image: url(/wwwroot/img/products/bg_sanpham_6.jpg); ">

    <div class="breadcrumb-overlay"></div>
    <div class="breadcrumb-content">
        <div class="wrapper">
            <div style="text-align: center;">
                <div class="breadcrumb-big">
                    <h2 style="font-size: 38px;">
                        GIỎ HÀNG
                    </h2>

                </div>
                <div class="breadcrumb-small" style="font-size: 20px; padding-top: 10px;">
                    <a href="@Url.Action("Index","Home")" title="">TRANG CHỦ</a>


                    <span aria-hidden="true">/</span>
                    <span>GIỎ HÀNG</span>


                </div>
            </div>
        </div>
    </div>
</section>
<!-- banner end -->
<!-- cart section start here -->

<div class="m-container-content" style="margin-left:90px; margin-right:90px">
    <div class="m-account-ft-group" style="margin-top: 40px;">
        <div class="flex-jsb" style="align-items:center;">
            <div class="m-account-ft-title">CHI TIẾT GIỎ HÀNG</div>
            @if (Model.Count > 0)
            {
                <a href="@Url.Action("XoaTatCaGioHang","Cart")" class="m-cart-delete-all" >
                    Xóa giỏ hàng
                </a>
            }
        </div>
        @if (Model.Count > 0)
        {
            <div class="m-account-ft-content">
                <table class="m-table-fe" style="margin-top: 20px;">
                    <thead>
                        <tr>
                            <th class="first">Mã</th>
                            <th>Ảnh sản phẩm</th>
                            <th>Tên sản phẩm</th>
                            <th>Giá</th>
                            <th style="max-width: 106px;">Giảm</th>
                            <th>Số lượng</th>
                            <th>Tính Tiền</th>
                            <th class="last">Hành động</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td style="border-left:none !important;"><div>@item.iMaHang</div></td>
                                <td>
                                    <div class="">
                                        @{
                                            string ImagePath = "";
                                            if (item.sAnh != null) { ImagePath = "~/wwwroot/img/sanpham/" + item.sAnh; }
                                            else { ImagePath = "~/wwwroot/img/sanpham/no-image-news.png"; }
                                        }
                                        <img src="@Url.Content(ImagePath)" class="m-img-order" style="width: 60px; height: 60px;" />

                                    </div>
                                </td>
                                <td>
                                    <div>
                                        @item.sTenHang
                                    </div>
                                </td>
                                <td>
                                    <div>

                                        @string.Format("{0:#,##}", item.dDonGia) <u>đ</u>
                                    </div>
                                </td>
                                <td>
                                    <div>
                                        @item.gGiamGia%
                                    </div>
                                </td>
                                @using (Html.BeginForm("CapNhatGioHang", "Cart", new { @MaHang = item.iMaHang }))
                                {
                                    <td>
                                        <div>
                                            <div style="min-width: 106px; max-width: 106px;">
                                                <a href="@Url.Action("GiamSPGioHang",new { MaHang = item.iMaHang})" title="Giảm đi một sản phẩm" class="m-cart-number- div-cart">
                                                    <i class="fas fa-minus"></i>
                                                </a>
                                                <input type="number" min="1" name="txtSoLuongDat" value="@item.iSoLuong" class="m-input-carts" />
                                                <a href="@Url.Action("TangSPGioHang",new { MaHang = item.iMaHang})" title="Tăng lên một sản phẩm" class="m-cart-number- plus-cart">
                                                    <i class="fas fa-plus"></i>
                                                </a>

                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div>
                                            @string.Format("{0:#,##}", item.dThanhTien) <u>đ</u>
                                        </div>
                                    </td>
                                    <td class="m-table-function-s " style="width: 161px; max-width: 161px;">

                                        <a href="@Url.Action("Details","Products",  new { id = item.iMaHang })" title="Xem chi tiết sản phẩm">
                                            <i class="fas fa-eye" style="color: #26845D;"></i>

                                        </a> &nbsp;
                                        <button type="submit" title="Sửa số lượng trong giỏ hàng" style="border:unset;background:unset;">

                                            <i class="far fa-edit" style="color: #E2E60C; "></i>

                                        </button>&nbsp;
                                        <a href="@Url.Action("XoaGioHang",new { iMaHang = item.iMaHang})"
                                           onclick="return confirm('Bạn có chắc muốn xóa sản phẩm này khỏi giỏ hàng ?');"
                                           title="Xóa sản phẩm trong giỏ hàng">
                                            <i class="fas fa-trash-alt" style="color: red;"></i>
                                        </a>
                                    </td>
                                }
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="m-account-ft-content">
                <div class="flex-jc">
                    <div style="border-bottom: 3px solid #26845D; margin: 40px; width: 500px;"></div>
                </div>
                <div class="flex-jc">
                    <div class="flex-jsb" style="width: 400px;">
                        <div style="font-size: 23px; font-weight: 500; color: #18543B;">Tổng tiền :</div>
                        <div style="font-size: 23px; color: red;">
                            @string.Format("{0:#,##}", @ViewBag.TongTien) <u>đ</u>

                        </div>
                    </div>
                </div>

            </div>

            <div class="m-account-ft-content flex-jc">
                <a href="@Url.Action("PayDetail","Orders",  new { tongtien = ViewBag.TongTien })" class=" m-cart-funtion-last flex-jc">
                    Thanh toán
                </a>
            </div>
        }
        else
        {
            <div class="m-account-ft-content">
                <div style="color: #73a33e; font-size: 20px; font-weight: 500; text-align:center;">Không có sản phẩm trong giỏ!</div>
            </div>
        }

    </div>
</div>