Hoai_Vitaminhouse/Hoai_Vitaminhouse/Models/Product.cs
namespace Hoai_Vitaminhouse.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Product")]
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        [Key]
        public int ProductId { get; set; }

        [Required(ErrorMessage = "Tên sản phẩm không được để trống!")]
        [StringLength(100)]
        public string ProductName { get; set; }

        [Required(ErrorMessage = "Ảnh của sản phẩm không được để trống!")]
        [StringLength(50)]
        public string ProductImage { get; set; }

        [Required(ErrorMessage = "Đơn vị sản phẩm không được để trống!")]
        [StringLength(50)]
        public string ProductUnit { get; set; }

        [Required(ErrorMessage = "Tên nhà cung cấp không được để trống!")]
        [StringLength(100)]
        public string ProductProviders { get; set; }

        [Required(ErrorMessage = "Giá tiền của sản phẩm không được để trống!")]
        [Column(TypeName = "money")]
        [Range(0, Double.PositiveInfinity, ErrorMessage = "Gía tiền không thể nhỏ hơn 0")]
        public decimal ProductPrice { get; set; }

        [Required(ErrorMessage = "Số lượng sản phẩm không được để trống!")]
        public int ProductNumber { get; set; }

        [Column(TypeName = "ntext")]
        [DataType(DataType.MultilineText)]
        public string ProductDescription { get; set; }

        [Range(0, 100, ErrorMessage ="Phần trăm giảm giá nằm từ khoảng >=0 hoặc <=100" )]
        public double? ProductDiscount { get; set; }

        public int CategoryId { get; set; }

        public virtual Category Category { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Areas/Admin/Controllers/ProductsController.cs
using Hoai_Vitaminhouse.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hoai_Vitaminhouse.Areas.Admin.Controllers
{
    public class ProductsController : Controller
    {
        private Vitaminhouse db = new Vitaminhouse();

        public ActionResult Index(int? page)
        {
            if (Session["admin"] != null)
            {
                var hangs = db.Products.Select(h => h).OrderBy(p => p.ProductId); ;

                int pageSizeFix = 7; //Kích thước trang
                int pageNumber = (page ?? 1);

                return View(hangs.ToPagedList(pageNumber, pageSizeFix));
            }
            else
            {
                return Redirect("/Admin/Access/Login");
            }

        }

        public ActionResult Details(int? id)
        {
            if (Session["admin"] != null)
            {
                if (id == null)
                {
                    return Redirect("/Admin/Products/Index");
                }
                Product hang = db.Products.Find(id);
                if (hang == null)
                {
                    return Redirect("/Admin/Products/Index");
                }
                return View(hang);
            }
            else
            {
                return Redirect("/Admin/Access/Login");
            }
        }

        [HttpGet]
        public ActionResult Create()
        {
            if (Session["admin"] != null)
            {
                ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName");
                return View();
            }
            else
            {
                return Redirect("/Admin/Access/Login");
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product hang)
        {
            try
            {
                hang.ProductImage = null;
                var f = Request.Files["ImageFilesss"];
                if (f != null && f.ContentLength > 0)
                {
                    string FileName = System.IO.Path.GetFileName(f.FileName);
                    string UploadPath = Server.MapPath("~/wwwroot/img/sanpham/" + FileName);

                    f.SaveAs(UploadPath);
                    hang.ProductImage = FileName;
                    db.Products.Add(hang);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName");
                    ViewBag.ErrorCreateHang = "Cần phải upload file ảnh!";
                    return View(hang);
                }
                

            }
            catch (Exception ex)
            {
                ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName");
                ViewBag.ErrorCreateHang = "Có lỗi xảy ra ! " + ex.Message;
                return View(hang);
            }
        }


        public ActionResult Delete(int? id)
        {
            if (Session["admin"] != null)
            {
                if (id == null)
                {
                    return Redirect("/Admin/Products/Index");
                }
                Product hang = db.Products.Find(id);
                if (hang == null)
                {
                    return Redirect("/Admin/Products/Index");
                }
                return View(hang);
            }
            else
            {
                return Redirect("/Admin/Access/Login");
            }
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product hang = db.Products.Find(id);
            try
            {
                db.Products.Remove(hang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ViewBag.ErrorDeleteHang = "Lỗi không xóa được sản phẩm! ";
                return View("Delete", hang);
            }

        }

        public ActionResult Edit(int? id)
        {
            if (Session["admin"] != null)
            {

                if (id == null)
                {
                    return Redirect("/Admin/Products/Index");
                }
                Product hang = db.Products.Find(id);
                if (hang == null)
                {
                    return Redirect("/Admin/Products/Index");
                }

                ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName", hang.CategoryId);
                return View(hang);
            }
            else
            {
                return Redirect("/Admin/Access/Login");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product hang)
        {
            try
            {
                var f = Request.Files["ImageFilesss"];
                if (f != null && f.ContentLength > 0)
                {
                    string FileName = System.IO.Path.GetFileName(f.FileName);
                    string UploadPath = Server.MapPath("~/wwwroot/img/sanpham/" + FileName);

                    f.SaveAs(UploadPath);
                    hang.ProductImage = FileName;
                }
                db.Entry(hang).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.ErrorEditHang = "Lỗi sửa sản phẩm!";
                ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "CategoryName");
                return View(hang);
            }
        }
    }
}

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Controllers/CartController.cs
using Hoai_Vitaminhouse.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hoai_Vitaminhouse.Controllers
{
    public class CartController : Controller
    {


        Vitaminhouse db = new Vitaminhouse();
        public List<Cart> Laygiohang()
        {
            if (!(Session["GioHang"] is List<Cart> lstGioHang))
            {
                lstGioHang = new List<Cart>();
                Session["GioHang"] = lstGioHang;
            }
            return lstGioHang;
        }
        // GET: GioHang

        public ActionResult ThemGioHang(int iMaHang, string strURL)
        {
            // lấy session gio hang
            List<Cart> lstGioHang = Laygiohang();
            Cart sanpham = lstGioHang.Find(n => n.iMaHang == iMaHang);
            if (sanpham == null)//Trong giỏ hàng chưa có sản phẩm này
            {
                sanpham = new Cart(iMaHang);
                lstGioHang.Add(sanpham);
                return Redirect(strURL);
            }
            else//Trong giỏ hàng có sản phẩm này rồi
            {
                Product hang = db.Products.Single(n => n.ProductId == iMaHang);
                if (hang.ProductNumber > sanpham.iSoLuong)//Nếu sản phẩm trong giỏ hàng nhỏ hơn sản phẩm có thì tăng lên 1
                {
                    sanpham.iSoLuong++;
                }
                else //Nếu mà không lớn hơn thì nó chỉ bắt buộc là bằng thôi 
                {
                    sanpham.iSoLuong = hang.ProductNumber;
                }

                return Redirect(strURL);
            }
        }


        private double TongTien()
        {
            double iTongTien = 0;
            List<Cart> lstGioHang = Session["GioHang"] as List<Cart>;
            if (lstGioHang != null)
            {
                iTongTien = lstGioHang.Sum(n => n.dThanhTien);
            }
            return iTongTien;
        }

        public ActionResult Index()
        {
            List<Cart> lstGioHang = Laygiohang();
            ViewBag.TongTien = TongTien();
            return View(lstGioHang);
        }
        public ActionResult XoaGioHang(int iMaHang)
        {
            // lay gio hang tu session
            List<Cart> lstGioHang = Laygiohang();
            Cart sanpham = lstGioHang.SingleOrDefault(n => n.iMaHang == iMaHang);
            if (sanpham != null)
            {
                lstGioHang.RemoveAll(n => n.iMaHang == iMaHang);
            }
            return RedirectToAction("/Index");
        }

        public ActionResult CapNhatGioHang(int MaHang, FormCollection f)
        {
            List<Cart> lstGioHang = Laygiohang();
            Cart sanpham = lstGioHang.SingleOrDefault(n => n.iMaHang == MaHang);
            if (sanpham != null)
            {
                Product hang = db.Products.Single(n => n.ProductId == MaHang);
              
                int soluongmuon = int.Parse(f["txtSoLuongDat"].ToString());
                if (hang.ProductNumber < soluongmuon)//Nếu số lượng muốn mà nhiều hơn số lượng có thì số lượng sẽ bằng số lượng tối đa
                {
                    sanpham.iSoLuong = hang.ProductNumber;
                }
                else
                {
                    sanpham.iSoLuong = soluongmuon;
                }
                    
            }
            return RedirectToAction("Index");

        }

        public ActionResult TangSPGioHang(int MaHang)
        {
            List<Cart> lstGioHang = Laygiohang();
            Cart sanphamInGio = lstGioHang.SingleOrDefault(n => n.iMaHang == MaHang);
            if (sanphamInGio != null)//Nếu tồn tại sản phẩm
            {
                Product hang = db.Products.Single(n => n.ProductId == MaHang);
                if (hang.ProductNumber > sanphamInGio.iSoLuong)
                {
                    sanphamInGio.iSoLuong++;//Nếu mà nó vẫn đang nhỏ hơn số lượng có thì nó tăng lên 1
                }
            }
            return RedirectToAction("Index");
        }
        public ActionResult GiamSPGioHang(int MaHang)
        {
            List<Cart> lstGioHang = Laygiohang();
            Cart sanphamInGio = lstGioHang.SingleOrDefault(n => n.iMaHang == MaHang);
            if (sanphamInGio != null)//Nếu tồn tại sản phẩm
            {
                Product hang = db.Products.Single(n => n.ProductId == MaHang);
                if (sanphamInGio.iSoLuong > 1)
                {
                    sanphamInGio.iSoLuong--;//Nếu mà nó vẫn lớn hơn 1 thì trừ đi một sản phẩm trong giỏ
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult XoaTatCaGioHang()
        {
            List<Cart> lstGioHang = Laygiohang();
            lstGioHang.Clear();
            return RedirectToAction("/Index");
        }

    }
}

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Controllers/CategoriesController.cs
using Hoai_Vitaminhouse.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hoai_Vitaminhouse.Controllers
{
    public class CategoriesController : Controller
    {
        private Vitaminhouse db = new Vitaminhouse();

        // GET: DanhMucs/Details/5
        public ActionResult Details(int? id, int? page)
        {
            if (id == null)
            {
                return Redirect("/NotFound/Index");
            }
            Category danhMuc = db.Categories.Find(id);
            if (danhMuc == null)
            {
                return Redirect("/NotFound/Index");
            }

            //Lấy ra danh sách có số lượng giảm dần
            var listProduct = db.Products.Where(p => p.Category.CategoryId == id).OrderByDescending(p => p.ProductId);
            ViewBag.Category = danhMuc;

            int pageSizeFix = 8; //Kích thước trang
            int pageNumber = (page ?? 1);

            return View(listProduct.ToPagedList(pageNumber, pageSizeFix));

        }
    }
}

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Controllers/ProductsController.cs
using Hoai_Vitaminhouse.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hoai_Vitaminhouse.Controllers
{
    public class ProductsController : Controller
    {
        private Vitaminhouse db = new Vitaminhouse();

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Product sp = db.Products.Find(id);
            if (sp == null)
            {
                return Redirect("/NotFound/Index");
            }
            return View(sp);
        }


        public ActionResult FindProducts(string keyword, int? page)
        {
            if (keyword == null)
            {
                keyword = "";
            }
            ViewBag.TukhoaTimkiem = keyword;
            var hangs = db.Products.Where(p => p.ProductName.Contains(keyword)).OrderByDescending(p => p.ProductId);


            int pageSizeFix = 8; //Kích thước trang
            int pageNumber = (page ?? 1);

            return View(hangs.ToPagedList(pageNumber, pageSizeFix));


        }
    }
}

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Views/Products/Details.cshtml
@model  Hoai_Vitaminhouse.Models.Product

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="m-title-ca" style="margin-left: 90px;">
        <a  href="@Url.Action("Index", "Home")" class="m-title-2" >Trang chủ</a>&nbsp;
        <i class="fas fa-chevron-right"></i> &nbsp;
        <a href="@Url.Action("Details","Categories",new { id = Model.Category.CategoryId})"  class="m-title-2" >@Model.Category.CategoryName</a> &nbsp;
        <i class="fas fa-chevron-right"></i> &nbsp;
        <div>@Model.ProductName</div> &nbsp;

    </div>
    <div class="m-product-detail">
        <div class="m-product-top">
            <div class="m-product-group-img" style="position:relative;">
                <div class="m-product-img-detail" >
                    @{
                        string ImagePath = "";
                        if (Model.ProductImage != null) { ImagePath = "~/wwwroot/img/sanpham/" + Model.ProductImage; }
                        else { ImagePath = "~/wwwroot/img/sanpham/no-image-news.png"; }
                    }
                    <img src="@Url.Content(ImagePath)" />
                </div>
                @if (Model.ProductDiscount > 0)
                { 
                    <div class="m-pr-discount">
                        <div class="m-pr-title-discount">GIẢM</div>
                        <div class="m-pr-number-discount">
                            @Model.ProductDiscount%
                        </div>
                    </div>
                 }
                
            </div>
            <div class="m-product-content-detail">
                <div class="m-pd-top">
                    <div class="m-pd-name"> @Model.ProductName</div>
                    <div class="m-pd-provider">@Model.ProductProviders</div>
                </div>
                <div style="border-bottom: 1px solid #e1e3e4; margin: 24px 0; "></div>
                <div class="m-pd-bottom">
                    <div class="m-pr-item">
                        <div class="m-pr-name-">Tình trạng:</div>
                          @if (Model.ProductNumber > 0)
                          {
                              <div style="display:flex; align-items:center;">
                                <div class="m-pr-status-has-icon"></div>
                                <div class="m-pr-status-has-title">Còn hàng</div>
                              </div>
                          }
                          else { 
                              <div style="display:flex; align-items:center;">
                                <div class="m-pr-status-no-icon"></div>
                                <div class="m-pr-status-no-title">Hết hàng</div>
                              </div>
                          }  
                    </div>
                    <div class="m-pr-item">
                        <div class="m-pr-name-">Đơn vị:</div>
                        <div class="m-pr-unit">@Model.ProductUnit</div>
                    </div>
                   
                    <div class="m-pr-item">
                        <div class="m-pr-name-">Giá:</div>
                        <div style="display:flex;">
                            @if (Model.ProductDiscount > 0)
                            {
                              
                                decimal priceDiscount = (decimal)Model.ProductDiscount * Model.ProductPrice / 100;
                                decimal priceLast = Model.ProductPrice - priceDiscount;

                                <div class="m-pr-price-last">@string.Format("{0:#,##}", priceLast) <u>đ</u></div>
                                <div class="m-pr-price-first"> @string.Format("{0:#,##}", Model.ProductPrice) <u>đ</u></div>
                            }
                            else
                            {
                                <div class="m-pr-price-last"> @string.Format("{0:#,##}", Model.ProductPrice) <u>đ</u></div>
                            }


                        </div>
                    </div>
                    <div class="m-fucntion-pr-group">
                        @if (Model.ProductNumber > 0)
                        {
                            <a href=@Url.Action("ThemGioHang", "Cart", new { iMaHang = Model.ProductId, strURL = Request.Url.ToString() }) class="m-function-item-pr" style="background: #26845D;">

                                <i class="fas fa-shopping-cart"></i> &nbsp;&nbsp;
                                <div>
                                    Thêm vào giỏ
                                </div>
                            </a>
                        }
                        else
                        {
                            <a href="" class="m-function-item-pr" style="background: #26845D; opacity: 0.8;">
                                <div>
                                    Hết hàng
                                </div>
                            </a>
                        }

                        <a href="@Url.Action("Details","Categories",new { id = Model.Category.CategoryId})" class="m-function-item-pr" style="background: #73a33e;">
                            <i class="fas fa-long-arrow-alt-left"></i> &nbsp;&nbsp;
                            <div>
                                Xem sản phẩm khác
                            </div>
                        </a>
                    </div>
                </div>
                <div class="m-pd-finish">
                    <div>
                        <div class="m-pd-title-"><i class="fas fa-check-circle"></i>Ship COD Toàn quốc</div>
                        <div class="m-pd-title-"><i class="fas fa-check-circle"></i>Ship nhanh trong ngày TP.HCM</div>
                        <div class="m-pd-title-"><i class="fas fa-check-circle"></i>Thiết kế và gói quà tặng</div>
                        <div class="m-pd-title-"><i class="fas fa-check-circle"></i>Cung cấp hàng giá sỉ cho shop</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="m-product-bottom">
            <div class="m-pr-description">Mô tả</div>
            <p class="m-descr">
                @Model.ProductDescription
            </p>
            <p class="m-descr"> * * * </p>
        </div>
    </div>

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Views/Products/FindProducts.cshtml
@model PagedList.IPagedList<Hoai_Vitaminhouse.Models.Product>
@using PagedList.Mvc;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="breadcrumb-wrapper" class="breadcrumb-w-img" style="background-image: url(/wwwroot/img/products/bg_sanpham_6.jpg); ">
    <div class="breadcrumb-overlay"></div>
    <div class="breadcrumb-content">
        <div class="wrapper">
            <div style="text-align: center;">
                <div class="breadcrumb-big">
                    <h2 style="font-size: 38px;">
                        TÌM KIẾM
                    </h2>
                </div>
                <div class="breadcrumb-small" style="font-size: 20px; padding-top: 10px;">
                    <a href="@Url.Action("Index","Home")" title="">TRANG CHỦ</a>
                    <span aria-hidden="true">/</span>
                    <span>TÌM KIẾM</span>
                    <span aria-hidden="true">/</span>
                    <span>@ViewBag.TukhoaTimkiem</span>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="m-container-product" style=" display: flex; justify-content: center;">
    <div class="m-product-group">
        @foreach (var item in Model)
        {
            <div class="m-product-item">
                <div class="m-product-img">
                    <a href="@Url.Action("Details","Products",  new { id = item.ProductId })">
                        @{
                            string ImagePath = "";
                            if (item.ProductImage != null)
                            {
                                ImagePath = "~/wwwroot/img/sanpham/" + item.ProductImage;
                            }
                            else { ImagePath = "~/wwwroot/img/sanpham/no-image-news.png"; }
                        }

                        <img src="@Url.Content(ImagePath)" height="250" />
                    </a>
                </div>
                @if (item.ProductDiscount > 0)
                {
                    <div class="m-product-discount">
                        <div class="m-title-discount">GIẢM</div>
                        <div class="m-number-discount">
                            @item.ProductDiscount%
                        </div>
                    </div>
                }
                <div class="m-product-content">
                    <div class="m-product-name">
                        <a href="@Url.Action("Details","Products",  new { id = item.ProductId })">  @item.ProductName</a>
                    </div>
                    <div class="m-product-price-group">
                        @if (item.ProductDiscount > 0)
                        {
                            decimal priceDiscount = (decimal)@item.ProductDiscount * @item.ProductPrice / 100;
                            decimal priceLast = @item.ProductPrice - priceDiscount;

                            <div class="m-product-price">@string.Format("{0:#,##}", priceLast) <u>đ</u></div>
                            <div class="m-product-last"> @string.Format("{0:#,##}", item.ProductPrice) <u>đ</u></div>
                        }
                        else
                        {
                            <div class="m-product-price">@string.Format("{0:#,##}", item.ProductPrice) <u>đ</u></div>
                        }
                    </div>
                </div>
                <a href="htm.html">
                    <div class="m-function-product">

                        <i class="fas fa-shopping-cart"></i> &nbsp;&nbsp;
                        <div class="m-function-title">THÊM VÀO GIỎ</div>

                    </div>
                </a>
            </div>
        }

    </div>
</div>

<div class="m-paging-group">

    @Html.PagedListPager(Model, page => Url.Action("FindProducts", new { page = page, keyword = ViewBag.TukhoaTimkiem }), new PagedListRenderOptions()
    {
        UlElementClasses = new string[] { "store-pagination" },
    });
</div>