Hoai_Vitaminhouse/Hoai_Vitaminhouse/Controllers/AccountsController.cs
using Hoai_Vitaminhouse.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hoai_Vitaminhouse.Controllers
{
    public class AccountsController : Controller
    {
        private Vitaminhouse db = new Vitaminhouse();

        public ActionResult Logout()
        {
            Session["user"] = null;
            return Redirect("/");
        }

        public ActionResult Login()
        {
            if (Session["user"] == null)
            {
                return View();
            }
            return Redirect("/");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(FormCollection frm)
        {
            if (ModelState.IsValid)
            {
                string email = frm["email"];
                string password = frm["password"];

                Account user = db.Accounts.Where(s => s.AccountEmail.Equals(email) && s.AccountPassword.Equals(password)).SingleOrDefault();
                if (user != null)
                {
                    if (user.AccountStatus)
                    {
                        Session["user"] = user;//Thực hiện gán vào session
                        return Redirect("/");
                    }
                    else
                    {
                        ViewBag.errorLogin = "Tài khoản của bạn đang bị khóa!";
                    }
                }
                else
                {
                    ViewBag.errorLogin = "Vui lòng kiểm tra lại email hoặc mật khẩu! ";
                }

            }
            return View();
        }

        public ActionResult Register()
        {
            if (Session["user"] == null)
            {
                return View();
            }
            return Redirect("/");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "AccountName,AccountPhone,AccountEmail,AccountPassword,AccountAddress")] Account taiKhoan, FormCollection frm)
        {
            try
            {
                string confirmPassword = frm["confirmPassword"];
                if (confirmPassword != taiKhoan.AccountPassword)
                {
                    ViewBag.errorRegister = "Mật khẩu xác nhận không khớp! ";
                    return View(taiKhoan);
                }

                var tkcheck = db.Accounts.Where(tk => tk.AccountEmail == taiKhoan.AccountEmail);
                if (tkcheck.Count() == 0)
                {
                    if (ModelState.IsValid)
                    {
                        taiKhoan.AccountStatus = true;//Tình trạng là đang mở hoạt động bình thường
                        taiKhoan.AccountRole = 1;//Tài khoản mặc định là tài khoản khách hàng
                        db.Accounts.Add(taiKhoan);
                        db.SaveChanges();
                    }
                    return RedirectToAction("Login");
                }
                else
                {
                    ViewBag.errorRegister = "Email đã tồn tại! ";
                    return View(taiKhoan);
                }
            }
            catch (Exception ex)
            {
                ViewBag.errorRegister = "Lỗi " + ex.Message;
                return View(taiKhoan);
            }
        }


        public ActionResult ChangeInfo()
        {
            if (Session["user"] != null)
            {
                Account taiKhoan = Session["user"] as Account;
                return View(taiKhoan);
            }
            return Redirect("/");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangeInfo([Bind(Include = "AccountId,AccountName,AccountPhone,AccountEmail,AccountPassword,AccountAddress, AccountRole, AccountStatus")] Account taiKhoan)
        {
            try
            {
                if (taiKhoan.AccountName.Trim() == "")
                {
                    ViewBag.errorUpdateTaikhoan = "Họ tên không được để trống! ";
                    return View(taiKhoan);
                }
                var tkcheck = db.Accounts.Where(tk => (tk.AccountEmail == taiKhoan.AccountEmail) && tk.AccountId != taiKhoan.AccountId);
                if (tkcheck.Count() == 0)
                {
                    db.Entry(taiKhoan).State = EntityState.Modified;
                    db.Configuration.ValidateOnSaveEnabled = false;
                    db.SaveChanges();

                    Session["user"] = taiKhoan;//Lưu lại thông tin của khi cập nhật

                    return RedirectToAction("Detail");
                }
                else
                {
                    ViewBag.errorUpdateTaikhoan = "Email đã được tài khoản khác sử dụng! ";
                    return View(taiKhoan);
                }
            }
            catch (Exception ex)
            {
                ViewBag.errorUpdateTaikhoan = "Lỗi " + ex.Message;
                return View(taiKhoan);
            }
        }

        public ActionResult ChangePassword()
        {
            if (Session["user"] != null)
            {
                Account taiKhoan = Session["user"] as Account;
                return View(taiKhoan);
            }
            return Redirect("/");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword([Bind(Include = "AccountId,AccountName,AccountPhone,AccountEmail,AccountPassword,AccountAddress, AccountRole, AccountStatus")] Account taiKhoan)
        {
            try
            {
                string cu = Request["oldPassword"];
                string moi = Request["newPassword"];
                string xacnhan = Request["confirmPassword"];

                if (cu != null && moi != null && xacnhan != null)
                {
                    if (cu != "" && moi != "" && xacnhan != "")
                    {
                        if (moi == xacnhan)
                        {
                            if (moi.Length >= 3 && moi.Length <= 30)
                            {
                                Account tk = Session["user"] as Account;//Lấy dữ liệu user đang lưu ở session
                                if (cu == tk.AccountPassword + "")
                                {
                                    taiKhoan.AccountPassword = moi;
                                    db.Entry(taiKhoan).State = EntityState.Modified;
                                    Session["user"] = taiKhoan;
                                    db.SaveChanges();
                                    return RedirectToAction("Detail");

                                }
                                else
                                {
                                    ViewBag.LoiMatKhau = "Mật khẩu cũ không khớp!";
                                    return View(taiKhoan);
                                }
                            }
                            else
                            {
                                ViewBag.LoiMatKhau = "Độ dài mật khẩu mới >=3 và <=30!";
                                return View(taiKhoan);
                            }
                        }
                        else
                        {
                            ViewBag.LoiMatKhau = "Mật khẩu mới và xác nhận không khớp!";
                            return View(taiKhoan);
                        }
                    }
                    else
                    {
                        ViewBag.LoiMatKhau = "Không được để trống trường dữ liệu nào!";
                        return View(taiKhoan);
                    }
                }
                else
                {
                    ViewBag.LoiMatKhau = "Không được để trống trường dữ liệu nào!";
                    return View(taiKhoan);
                }
            }
            catch (Exception ex)
            {
                ViewBag.LoiMatKhau = "Lỗi " + ex.Message;
                return View(taiKhoan);
            }
        }


        public ActionResult Detail()
        {
            if (Session["user"] != null)
            {
                Account taiKhoan = Session["user"] as Account;
                List<Order> listDonHang = db.Orders.Where(p => p.AccountId == taiKhoan.AccountId)
                                                   .OrderByDescending(p => p.OrderDate).ToList();

                ViewBag.listDonHangByMaTK = listDonHang;

                return View(taiKhoan);
            }
            return RedirectToAction("Login");
        }
    }
}

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Controllers/BaseController.cs
using Hoai_Vitaminhouse.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hoai_Vitaminhouse.Controllers
{
    public class BaseController : Controller
    {

        private Vitaminhouse db = new Vitaminhouse();
        public PartialViewResult _Navbar()
        {
           var catogories = db.Categories.Select(n => n);
           ViewBag.SoLuongGioHang = this.TongSoLuong();
            return PartialView(catogories);
        }
        private int TongSoLuong()
        {
            int iTongSoLuong = 0;
            List<Cart> lstGioHang = Session["GioHang"] as List<Cart>;
            if (lstGioHang != null)
            {
                iTongSoLuong = lstGioHang.Sum(n => n.iSoLuong);
            }
            return iTongSoLuong;
        }

    }
}

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Controllers/CartController.cs
using Hoai_Vitaminhouse.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hoai_Vitaminhouse.Controllers
{
    public class CartController : Controller
    {


        Vitaminhouse db = new Vitaminhouse();
        public List<Cart> Laygiohang()
        {
            if (!(Session["GioHang"] is List<Cart> lstGioHang))
            {
                lstGioHang = new List<Cart>();
                Session["GioHang"] = lstGioHang;
            }
            return lstGioHang;
        }
        // GET: GioHang

        public ActionResult ThemGioHang(int iMaHang, string strURL)
        {
            // lấy session gio hang
            List<Cart> lstGioHang = Laygiohang();
            Cart sanpham = lstGioHang.Find(n => n.iMaHang == iMaHang);
            if (sanpham == null)//Trong giỏ hàng chưa có sản phẩm này
            {
                sanpham = new Cart(iMaHang);
                lstGioHang.Add(sanpham);
                return Redirect(strURL);
            }
            else//Trong giỏ hàng có sản phẩm này rồi
            {
                Product hang = db.Products.Single(n => n.ProductId == iMaHang);
                if (hang.ProductNumber > sanpham.iSoLuong)//Nếu sản phẩm trong giỏ hàng nhỏ hơn sản phẩm có thì tăng lên 1
                {
                    sanpham.iSoLuong++;
                }
                else //Nếu mà không lớn hơn thì nó chỉ bắt buộc là bằng thôi 
                {
                    sanpham.iSoLuong = hang.ProductNumber;
                }

                return Redirect(strURL);
            }
        }


        private double TongTien()
        {
            double iTongTien = 0;
            List<Cart> lstGioHang = Session["GioHang"] as List<Cart>;
            if (lstGioHang != null)
            {
                iTongTien = lstGioHang.Sum(n => n.dThanhTien);
            }
            return iTongTien;
        }

        public ActionResult Index()
        {
            List<Cart> lstGioHang = Laygiohang();
            ViewBag.TongTien = TongTien();
            return View(lstGioHang);
        }
        public ActionResult XoaGioHang(int iMaHang)
        {
            // lay gio hang tu session
            List<Cart> lstGioHang = Laygiohang();
            Cart sanpham = lstGioHang.SingleOrDefault(n => n.iMaHang == iMaHang);
            if (sanpham != null)
            {
                lstGioHang.RemoveAll(n => n.iMaHang == iMaHang);
            }
            return RedirectToAction("/Index");
        }

        public ActionResult CapNhatGioHang(int MaHang, FormCollection f)
        {
            List<Cart> lstGioHang = Laygiohang();
            Cart sanpham = lstGioHang.SingleOrDefault(n => n.iMaHang == MaHang);
            if (sanpham != null)
            {
                Product hang = db.Products.Single(n => n.ProductId == MaHang);
              
                int soluongmuon = int.Parse(f["txtSoLuongDat"].ToString());
                if (hang.ProductNumber < soluongmuon)//Nếu số lượng muốn mà nhiều hơn số lượng có thì số lượng sẽ bằng số lượng tối đa
                {
                    sanpham.iSoLuong = hang.ProductNumber;
                }
                else
                {
                    sanpham.iSoLuong = soluongmuon;
                }
                    
            }
            return RedirectToAction("Index");

        }

        public ActionResult TangSPGioHang(int MaHang)
        {
            List<Cart> lstGioHang = Laygiohang();
            Cart sanphamInGio = lstGioHang.SingleOrDefault(n => n.iMaHang == MaHang);
            if (sanphamInGio != null)//Nếu tồn tại sản phẩm
            {
                Product hang = db.Products.Single(n => n.ProductId == MaHang);
                if (hang.ProductNumber > sanphamInGio.iSoLuong)
                {
                    sanphamInGio.iSoLuong++;//Nếu mà nó vẫn đang nhỏ hơn số lượng có thì nó tăng lên 1
                }
            }
            return RedirectToAction("Index");
        }
        public ActionResult GiamSPGioHang(int MaHang)
        {
            List<Cart> lstGioHang = Laygiohang();
            Cart sanphamInGio = lstGioHang.SingleOrDefault(n => n.iMaHang == MaHang);
            if (sanphamInGio != null)//Nếu tồn tại sản phẩm
            {
                Product hang = db.Products.Single(n => n.ProductId == MaHang);
                if (sanphamInGio.iSoLuong > 1)
                {
                    sanphamInGio.iSoLuong--;//Nếu mà nó vẫn lớn hơn 1 thì trừ đi một sản phẩm trong giỏ
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult XoaTatCaGioHang()
        {
            List<Cart> lstGioHang = Laygiohang();
            lstGioHang.Clear();
            return RedirectToAction("/Index");
        }

    }
}

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Controllers/CategoriesController.cs
using Hoai_Vitaminhouse.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hoai_Vitaminhouse.Controllers
{
    public class CategoriesController : Controller
    {
        private Vitaminhouse db = new Vitaminhouse();

        // GET: DanhMucs/Details/5
        public ActionResult Details(int? id, int? page)
        {
            if (id == null)
            {
                return Redirect("/NotFound/Index");
            }
            Category danhMuc = db.Categories.Find(id);
            if (danhMuc == null)
            {
                return Redirect("/NotFound/Index");
            }

            //Lấy ra danh sách có số lượng giảm dần
            var listProduct = db.Products.Where(p => p.Category.CategoryId == id).OrderByDescending(p => p.ProductId);
            ViewBag.Category = danhMuc;

            int pageSizeFix = 8; //Kích thước trang
            int pageNumber = (page ?? 1);

            return View(listProduct.ToPagedList(pageNumber, pageSizeFix));

        }
    }
}

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Views/Shared/_Footer.cshtml
<!-- ======= Footer ======= -->
<div class="m-footer" >
    <div class="m-footer-top">
        <div class="m-footer-left">
            <a>
                <img src="~/wwwroot/img/logos/logo_3.png" alt="" title="Vitaminhouse" class="img-fluid logo" width="100%" />
            </a>
            <p class="m-content-footer">
                <b>Vitamin House</b> là thương hiệu chuyên cung cấp sỉ và lẻ các sản phẩm ngoại nhập như bánh kẹo, trái cây, nước uống, đồ ăn tươi sống, thực phẩm đóng hộp… được nhập khẩu chính hãng từ các quốc gia uy tín như Mỹ, Pháp, Úc, Hàn Quốc, Nhật Bản
            </p>
        </div>
           
        <div class="m-footer-center">
            <h4>HỆ THỐNG CỬA HÀNG</h4>
            <ul>
                <li>
                    <a href="@Url.Action("Index","Home")">
                        <b>CỬA HÀNG CMT8</b><br>
                        ☎:0274 6568 777 📞: 0989 882 545<br>
                        ĐC: 563 CMT8, P15, Q10, Tp. HCM.

                    </a>
                </li>
                <br>
                <li>
                    <a href="@Url.Action("Index","Home")">
                        <strong>CỬA HÀNG QUANG TRUNG</strong><br>
                        ☎:02854 432 212 📞: 0984 741 875 <br>
                        ĐC: 330 Quang Trung, P10, Q.Gò Vấp, Tp. HCM.
                    </a>
                </li>
                <br>
                <li>
                    <a href="@Url.Action("Index","Home")">
                        <strong>CỬA HÀNG PHẠM VIẾT CHÁNH</strong><br>
                        ☎:02854 034 142 📞: 0989 882 545<br>
                        ĐC: 219A Phạm Viết Chánh, P.Nguyễn Cư Trinh, Q.1, TP.HCM.
                    </a>
                </li>
                <br>
            </ul>
        </div>
       
        <div class="m-footer-right" style="padding-right: 70px;">
            <h4>LIÊN KẾT NHANH</h4>
            <ul style="min-width: 180px;">
                @if (Session["user"] == null)
                {
                    <li>@Html.ActionLink("Trang chủ", "Index", "Home")</li>
                    <li>@Html.ActionLink("Đăng nhập", "Login", "Accounts")</li>
                    <li>@Html.ActionLink("Đăng ký", "Register", "Accounts")</li>
                    <li>@Html.ActionLink("Truy cập trang quản trị", "Access", "Admin")</li>
                }
                else
                {
                                    
                    <li>@Html.ActionLink("Xem thông tin cá nhân", "Detail", "Accounts")</li>
                    <li>@Html.ActionLink("Sửa tài khoản", "ChangeInfo", "Accounts")</li>
                    <li>@Html.ActionLink("Đổi mật khẩu", "ChangePassword", "Accounts")</li>
                    <li>@Html.ActionLink("Đăng xuất", "Logout", "Accounts")</li>
                    <li>@Html.ActionLink("Truy cập trang quản trị", "Access", "Admin")</li>
                }
            </ul>
        </div>
        
    </div>

    <div class="m-footer-bottom">
        <div>
            Copyright  <i class="far fa-copyright"></i> 2022 Phạm Thị Hoài
        </div>
    </div>

</div>
<!-- End Footer -->

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>

    <title>Cửa Hàng Đồ ăn vặt Vitamin House</title>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta name="viewport" content="width=device-width, shrink-to-fit=9" />

    <meta name="description" content="Home supermarket" />

    <meta name="author" content="Home Grocerino" />

    <link rel="icon" type="image/png" href="~/wwwroot/img/logos/logo_3.png" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @{Html.RenderPartial("_Style");}


</head>

<body class="grocino-home">

    <!-- Top header start -->
    @{ Html.RenderAction("_Navbar", "Base"); }
    <!-- Start Hero Slide-->


    @RenderBody()


    <!-- ======= Footer ======= -->
    @Html.Partial("_Footer")
    <!-- End Footer -->
    <!-- JS -->
    @{Html.RenderPartial("_Script");}

    <script async src="https://www.googletagmanager.com/gtag/js?id=G-GF3SVYD2YD"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'G-GF3SVYD2YD');
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>
</html>

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Views/Shared/_Navbar.cshtml
@model IEnumerable<Hoai_Vitaminhouse.Models.Category>

<header id="header" class="fixed-top">
    <div class="p1 m-logo-fe">
        <div class="container d-flex align-items-center ">
            <a href="@Url.Action("Index","Home")" class="logo me-auto "><img src="~/wwwroot/img/logos/logo_3.png" alt="" style='max-width:140px' ></a>
        </div>
    </div>
    <div class="p2">
        <ul id="menu">
            <div class="inner">
                <div class="header-navbar-wrapper">
                    <div class="header-navbar text-right">
                        <ul class="no-bullets">
                            <li><a href="@Url.Action("Index", "Home")"><span class="m-title-navbar">TRANG CHỦ</span></a></li>
                            <li>
                                <a><span class="m-title-navbar">DANH MỤC SẢN PHẨM&nbsp;<i class="bi bi-chevron-down" style="color:white !important;"></i></span> </a>
                                <ul class="m-catogory">
                                    @foreach (var item in Model)
                                        {
                                            <li><a href="@Url.Action("Details","Categories",new { id = item.CategoryId})"><span>@item.CategoryName</span></a></li>
                                         }
                                    

                                </ul>
                            </li>
                            <li><a href="@Url.Action("Index", "Newspapers")"><span class="m-title-navbar">BLOG VITAMIN</span></a></li>
                            <li><a href="@Url.Action("Introduce", "Home")"><span class="m-title-navbar">GIỚI THIỆU</span></a></li>
                            <li><a href="@Url.Action("Contact", "Home")"><span class="m-title-navbar">LIÊN HỆ</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </ul>
        
          </div>
    <nav id="navbar" class="navbar order-last order-lg-0">
        <a>
            <form class="m-form-search" action="/Products/FindProducts">
                <input type="text" id="keyword" name="keyword" placeholder="Tìm kiếm sản phẩm..." />
                <div class="m-icon-search">
                    <div>
                        <i class="fas fa-search" onclick="onSearch()"></i>
                    </div>
                </div>
            </form>
        </a>


        <ul class="dropdown">
            <a href="@Url.Action("Detail","Accounts")" ><span><i class="fas fa-user icons"></i></span></a>
            <ul>
                @if (Session["user"] == null)
                 {
                    <li>@Html.ActionLink("ĐĂNG NHẬP", "Login", "Accounts")</li>
                    <li>@Html.ActionLink("ĐĂNG KÝ", "Register", "Accounts")</li>
                 }
                else
                {
                    <li>@Html.ActionLink("XEM THÔNG TIN CÁ NHÂN", "Detail", "Accounts")</li>
                    <li>@Html.ActionLink("SỬA TÀI KHOẢN", "ChangeInfo", "Accounts")</li>
                    <li>@Html.ActionLink("ĐỔI MẬT KHẨU", "ChangePassword", "Accounts")</li>
                    <li>@Html.ActionLink("ĐĂNG XUẤT", "Logout", "Accounts")</li>
                }
                <li>@Html.ActionLink("TRUY CẬP TRANG QUẢN TRỊ", "Access", "Admin")</li>
            </ul>
        </ul>

        <a href="@Url.Action("Index","Cart")" style="position:relative">
            <i class="fas fa-cart-plus icons"></i>
            <span class="m-icon-cart">
                @ViewBag.SoLuongGioHang
                
            </span>
        </a>
        <!-- .navbar -->
    </nav>

</header>
<script>
    const onSearch = () => {
        const keyword = document.getElementById("keyword").value;
        window.location = `/Products/FindProducts?keyword=${keyword}`;
    }
</script>

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Views/Shared/_Script.cshtml
<script src="~/wwwroot/assets/js/popper.js"></script>

<script src="~/wwwroot/assets/js/jquery.js"></script>

<script src="~/wwwroot/assets/js/bootstrap.js"></script>

<script src="~/wwwroot/assets/js/dropdown.js"></script>

<script src="~/wwwroot/assets/js/semantic.js"></script>

<script src="~/wwwroot/assets/js/owl.carousel.js"></script>

<script src="~/wwwroot/assets/js/swiper.min.js"></script>

<script src="~/wwwroot/assets/js/vejcustome.js"></script>

<script src="~/wwwroot/assets/js/counter.js"></script>


<script src="~/wwwroot/assets/js/main.js"></script>

<!-- JS -->
<script src="~/wwwroot/assets/vendor/aos/aos.js"></script>
<script src="~/wwwroot/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/wwwroot/assets/vendor/glightbox/js/glightbox.min.js"></script>
<script src="~/wwwroot/assets/vendor/purecounter/purecounter.js"></script>
    <script src ="~/wwwroot/assets/vendor/swiper/swiper-bundle.min.js">
        </script>




    <script>
        var showErrorNotNumberProduct = function (event) {
            alert("Sản phẩm này đã hết hàng vui lòng chọn sản phẩm khác !");
        }
    </script>

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Views/Shared/_Slider.cshtml
<section id="hero">

        <div id="heroCarousel" data-bs-interval="5000" class="carousel slide carousel-fade" data-bs-ride="carousel">

            <div style="background-color:red !important; margin-left:500px !important;">
                <ol class="carousel-indicators" id="hero-carousel-indicators" style="padding-bottom: 30px !important; padding-left: 113px !important;"></ol>
            </div>

            <div class="carousel-inner" role="listbox">
                <div class="carousel-item active"><img src="~/wwwroot/img/slide/KY_NGHI_HE_CUNG_VITAMIN_1400x.jpg" alt="" width="100%"></div>
                <div class="carousel-item"><img src="~/wwwroot/img/slide/anh_tra_chieu.png" alt="" width="100%"></div>
                <div class="carousel-item"><img src="~/wwwroot/img/slide/KY_NGHI_HE_CUNG_VITAMIN_6024e19d-99e0-40d9-b66c-59b152ded659_1400x.png" alt="" width="100%"></div>
                <div class="carousel-item"><img src="~/wwwroot/img/slide/GDS_1400x.jpg" alt="" width="100%"></div>
                <div class="carousel-item"><img src="~/wwwroot/img/slide/z3320829911381_10e7707a51756f0618d59209b0e9d4b5_1400x.jpg" alt="" width="100%"></div>
                <div class="carousel-item"><img src="~/wwwroot/img/slide/BGF_1400x.jpg" alt="" width="100%"></div>
            </div>

            <!-- Button slide -->
            <a class="carousel-control-prev" role="button" data-bs-slide="prev">
                <span class="carousel-control-prev-icon bi bi-chevron-left" aria-hidden="true"></span>
            </a>
            <a class="carousel-control-next" role="button" data-bs-slide="next">
                <span class="carousel-control-next-icon bi bi-chevron-right" aria-hidden="true"></span>
            </a>
            <!-- End button slide -->

        </div>

</section>

Hoai_Vitaminhouse/Hoai_Vitaminhouse/Views/Shared/_Style.cshtml
<link href="~/wwwroot/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />

<link href="~/wwwroot/assets/css/bootstrap.min.css" rel="stylesheet" />

<link href="~/wwwroot/assets/css/owl.carousel.css" rel="stylesheet" />

<link rel="stylesheet" href="~/wwwroot/assets/unicons/css/unicons.css" />

<link href="~/wwwroot/css/style.css" rel="stylesheet" />

<link href="~/wwwroot/css/responsive.css" rel="stylesheet" />

<link href="~/wwwroot/assets/css/semantic.css" rel="stylesheet" />

<link href="~/wwwroot/assets/css/animate.min.css" rel="stylesheet" />

<link href="~/wwwroot/assets/css/swiper.min.css" rel="stylesheet" />

<link href="~/wwwroot/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">

<link href="~/wwwroot/assets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">

@* css add Vitaminhouse *@
<link href="~/wwwroot/css/css_vitaminhouse/navbar.css" rel="stylesheet" />
<link href="~/wwwroot/css/css_vitaminhouse/slider.css" rel="stylesheet" />
<link href="~/wwwroot/css/css_vitaminhouse/generate_fe.css" rel="stylesheet" />
<link href="~/wwwroot/css/css_vitaminhouse/footer.css" rel="stylesheet" />

<link href="~/wwwroot/css/css_vitaminhouse/_Home.css" rel="stylesheet" />

<link href="~/wwwroot/css/css_vitaminhouse/category/_Detail.css" rel="stylesheet" />
<link href="~/wwwroot/css/css_vitaminhouse/not_found/_Index.css" rel="stylesheet" />
<link href="~/wwwroot/css/css_vitaminhouse/product/_Detail.css" rel="stylesheet" />
<link href="~/wwwroot/css/css_vitaminhouse/newspaper/_Index.css" rel="stylesheet" />
<link href="~/wwwroot/css/css_vitaminhouse/newspaper/_Detail.css" rel="stylesheet" />
<link href="~/wwwroot/css/css_vitaminhouse/account/_Login.css" rel="stylesheet" />
<link href="~/wwwroot/css/css_vitaminhouse/account/_Detial.css" rel="stylesheet" />
<link href="~/wwwroot/css/css_vitaminhouse/cart/_Index.css" rel="stylesheet" />
@* close css add Vitaminhouse *@

<!-- Fonts -->

<link href="~/wwwroot/assets/fonts/style.css" rel="stylesheet" />

































<style>
</style>